server:
  port: 8000

spring:
  application:
    name: company-customer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: newpassword
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf-8
  rabbitmq:
    host: 127.0.0.1
    port: 5671
    username: lee
    password: 123456
management:
  security:
    enabled: false 
  #devtools:
   # restart:
    #  enabled: true  #打开热部署 
mybatis:
  type-aliases-package: com.bp.company.customer.pojo
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名，例如:表的字段名是book_name,那么pojo的字段名就是bookName    
eureka:
  instance:
    hostname: customer 
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:@project.version@
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:9000/eureka/

#company-provider: # 服务名称 
  #ribbon:
    #NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule 
#feign的日志    
logging:
  level:
    com.bp.company.customer.feignclient.CompanyFeignClient: debug

#断路器  不加这个好像也可以哦
feign:
  hystrix:
    enabled: true
    
#解决第一次启动时报超时，我们把时间设置长些
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout:  5000
  ConnectTimeout:  5000
env:
  dev4
  
            
            
